language: node_js
node_js:
  - "node"
  - "0.12"
  - "4"
  - "5"
sudo: false
before_install:
  - npm install --only=dev
services:
  - mongodb
install:
  - npm install
  - bower install
branches:
  only:
    - test
